export type OutputType = 'slideshow' | 'carousel' | 'hook-demo';
export type AssetCategory = 'PRODUCT' | 'TEMPLATE' | 'VIDEO' | 'DEMO' | 'OUTPUT' | 'MARKETING' | 'BRAND' | 'OTHER';
export interface App { sourceFolder: string | null; screenshotSource: string | null; screenshotsRefreshedAt: string | null; profileSource: 'manual' | 'app-store' | 'codex'; importedAt: string | null; id: string; name: string; oneLineDescription: string; audiences: string[]; features: string[]; contentAngles: string[]; tone: string[]; keywords: string[]; appStoreUrl: string; appleAppId: string | null; iconPath: string | null; subtitle: string; description: string; screenshots: string[]; category: string; developer: string; createdAt: string; updatedAt: string; }
export interface Asset { sourceUrl?:string|null; attribution?:string; sourceKind: 'app-store' | 'local' | 'upload' | 'pinterest' | 'dupe'; sourceKey: string | null; thumbnailPath: string | null; active: number; id: string; appId: string; filename: string; path: string; type: 'image' | 'video' | 'other'; category: AssetCategory; description: string; tags: string[]; subjects: string[]; style: string[]; useCases: string[]; orientation: 'portrait' | 'landscape' | 'square' | null; width: number | null; height: number | null; duration: number | null; contentHash: string | null; analysisStatus: string; createdAt: string; lastUsedAt: string | null; usageCount: number; }
export interface Slide { crop?:import('./crop').ImageCrop; imageZoom?:number; textY?:number; role?:string; id: string; position: number; headline: string; body: string; assetQuery: string; assetId: string | null; template: string; textEmphasis: string[]; }
export interface TimelineSegment { id: string; kind: 'HOOK' | 'DEMO' | 'RESULT' | 'CTA'; start: number; end: number; text: string; assetId: string | null; trimStart: number; trimEnd: number; }
export interface Project { style: Record<string, unknown>; batchId: string | null; conceptIndex: number | null; id: string; appId: string; name: string; type: OutputType; platform: string; concept: Record<string, unknown>; inspirationId: string | null; creativeFormatId: string | null; template: string; slides: Slide[]; timeline: TimelineSegment[]; createdAt: string; updatedAt: string; }
export interface Inspiration { id: string; platform: string; url: string; title: string; notes: string; creator: string; caption: string; localMediaPath: string | null; views: number | null; likes: number | null; comments: number | null; publishedAt: string | null; capturedAt: string; analysisStatus: string; hook: string; hookType: string; structure: string[]; visualMechanic: string; topics: string[]; creativeFormatId: string | null; }
export interface CreativeFormat { id: string; name: string; description: string; hookPattern: string; structure: string[]; visualMechanic: string; ctaPattern: string; firstSeen: string; lastSeen: string; exampleCount: number; }
export interface Trend { id: string; creativeFormatId: string; score: number; observationCount: number; niches: string[]; firstSeen: string; lastSeen: string; }
