CREATE TABLE apps (
 id TEXT PRIMARY KEY, name TEXT NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 100), oneLineDescription TEXT NOT NULL DEFAULT '',
 audiences TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(audiences)), features TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(features)), contentAngles TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(contentAngles)), tone TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(tone)), keywords TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(keywords)),
 appStoreUrl TEXT NOT NULL DEFAULT '', appleAppId TEXT, iconPath TEXT, subtitle TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', screenshots TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(screenshots)), category TEXT NOT NULL DEFAULT '', developer TEXT NOT NULL DEFAULT '', createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL
);
CREATE TABLE creative_formats (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', hookPattern TEXT NOT NULL DEFAULT '', structure TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(structure)), visualMechanic TEXT NOT NULL DEFAULT '', ctaPattern TEXT NOT NULL DEFAULT '', firstSeen TEXT NOT NULL, lastSeen TEXT NOT NULL, exampleCount INTEGER NOT NULL DEFAULT 0 CHECK(exampleCount >= 0));
CREATE TABLE inspirations (id TEXT PRIMARY KEY, platform TEXT NOT NULL, url TEXT NOT NULL, title TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', creator TEXT NOT NULL DEFAULT '', caption TEXT NOT NULL DEFAULT '', localMediaPath TEXT, views INTEGER, likes INTEGER, comments INTEGER, publishedAt TEXT, capturedAt TEXT NOT NULL, analysisStatus TEXT NOT NULL DEFAULT 'pending', hook TEXT NOT NULL DEFAULT '', hookType TEXT NOT NULL DEFAULT '', structure TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(structure)), visualMechanic TEXT NOT NULL DEFAULT '', topics TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(topics)), creativeFormatId TEXT REFERENCES creative_formats(id) ON DELETE SET NULL);
CREATE TABLE assets (id TEXT PRIMARY KEY, appId TEXT NOT NULL REFERENCES apps(id) ON DELETE RESTRICT, filename TEXT NOT NULL, path TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('image','video','other')), category TEXT NOT NULL DEFAULT 'OTHER' CHECK(category IN ('PRODUCT','TEMPLATE','VIDEO','DEMO','OUTPUT','MARKETING','BRAND','OTHER')), description TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(tags)), subjects TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(subjects)), style TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(style)), useCases TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(useCases)), orientation TEXT CHECK(orientation IN ('portrait','landscape','square')), width INTEGER, height INTEGER, duration REAL, contentHash TEXT, analysisStatus TEXT NOT NULL DEFAULT 'pending', createdAt TEXT NOT NULL, lastUsedAt TEXT, usageCount INTEGER NOT NULL DEFAULT 0 CHECK(usageCount >= 0));
CREATE TABLE projects (id TEXT PRIMARY KEY, appId TEXT NOT NULL REFERENCES apps(id) ON DELETE RESTRICT, name TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('slideshow','carousel','hook-demo')), platform TEXT NOT NULL DEFAULT '', concept TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(concept)), inspirationId TEXT REFERENCES inspirations(id) ON DELETE SET NULL, creativeFormatId TEXT REFERENCES creative_formats(id) ON DELETE SET NULL, template TEXT NOT NULL DEFAULT '', slides TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(slides)), timeline TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(timeline)), createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL);
CREATE TABLE trends (id TEXT PRIMARY KEY, creativeFormatId TEXT NOT NULL REFERENCES creative_formats(id) ON DELETE CASCADE, score REAL NOT NULL DEFAULT 0, observationCount INTEGER NOT NULL DEFAULT 0 CHECK(observationCount >= 0), niches TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(niches)), firstSeen TEXT NOT NULL, lastSeen TEXT NOT NULL);
CREATE INDEX assets_app ON assets(appId);
CREATE INDEX assets_hash ON assets(contentHash);
CREATE INDEX projects_app ON projects(appId);
CREATE INDEX inspirations_format ON inspirations(creativeFormatId);
CREATE INDEX trends_format ON trends(creativeFormatId);
