import Link from 'next/link';
import { StoreRefresh } from '@/components/store-refresh';
import { ScreenshotStrip } from '@/components/app-import';
import { mediaUrl } from '@/lib/import-types';
import { notFound } from 'next/navigation';
import { getApp } from '@/lib/server/apps';
import { PageHeading } from '@/components/page-heading';
import { DeleteApp } from '@/components/app-form';
export default async function Page({params}:{params:Promise<{id:string}>}){const app=getApp((await params).id);if(!app)notFound();return <><Link className="back-link" href="/apps">← All apps</Link><PageHeading eyebrow="APP MARKETING PROFILE" title={app.name} description={app.oneLineDescription||'A new voice in your studio.'} action={<Link className="button" href={`/apps/${app.id}/edit`}>Edit profile</Link>}/>{app.iconPath && <div className="saved-app-icon"><img src={mediaUrl(app.iconPath)} alt={`${app.name} icon`} width={80} height={80}/><p className="muted">{app.category} · {app.developer}<br/>{app.profileSource==='codex'?'Marketing profile drafted with Codex · editable':app.importedAt?'Imported from Apple':'Manual profile'}</p></div>}<div className="profile-details">{(['audiences','features','contentAngles','tone','keywords'] as const).map(key=><section key={key}><h2>{{audiences:'Audiences',features:'Features',contentAngles:'Content angles',tone:'Tone',keywords:'Keywords'}[key]}</h2>{app[key].length?<div className="tags">{app[key].map((value,i)=><span key={i}>{value}</span>)}</div>:<p className="muted">Room to define your {key==='contentAngles'?'content angles':key}.</p>}</section>)}<section><h2>App Store</h2>{app.appStoreUrl?<a className="inline-link" href={app.appStoreUrl} target="_blank" rel="noreferrer">View App Store listing ↗</a>:<p className="muted">No URL added yet.</p>}{app.subtitle && <p className="muted">{app.subtitle}</p>}{app.appleAppId && <p className="muted">Apple ID: {app.appleAppId}</p>}{!app.importedAt && app.appStoreUrl && <Link className="inline-link" href={`/apps/new?url=${encodeURIComponent(app.appStoreUrl)}`}>Import icon, screenshots & marketing profile →</Link>}</section></div>{app.importedAt && <section className="import-preview saved-store"><h2>App Store assets</h2><StoreRefresh appId={app.id}/><p className="muted">{app.screenshotSource==='live-storefront'?'From the current storefront · available in Library and Create':'Refresh to verify current screenshots'}</p><ScreenshotStrip paths={app.screenshots} name={app.name}/><details className="store-description"><summary>Original App Store description</summary><p>{app.description}</p></details></section>}<DeleteApp app={app}/></>;}
