'use client';
import {useAppSelection} from './use-app-selection';
import {isTemplateAsset} from '@/lib/asset-policy';
import { useEffect,useState } from 'react';
import type { App,Asset } from '@/lib/models';
export const assetUrl=(id:string,thumbnail=false)=>`/api/assets/${id}/media${thumbnail?'?thumbnail=1':''}`;
export function AssetLibrary({apps}:{apps:App[]}) {
 const [appId,setAppId]=useAppSelection(apps);const [assets,setAssets]=useState<Asset[]>([]);const [folders,setFolders]=useState<string[]>([]);const [folder,setFolder]=useState('');
 const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [category,setCategory]=useState('OTHER');const [viewer,setViewer]=useState<Asset|null>(null);
 async function load(id:string) {const response=await fetch(`/api/assets?appId=${id}`);const data=await response.json();if(!response.ok)throw new Error(data.error);setAssets(data.assets);setFolders(data.folders);setFolder(data.folder||'');}
 useEffect(()=>{if(appId)void load(appId).catch(error=>setMessage(error.message));},[appId]);
 const filtered=assets.filter(asset=>!isTemplateAsset(asset)).filter(asset=>`${asset.filename} ${asset.description} ${asset.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="library-controls"><label>App<select value={appId} onChange={event=>{setAppId(event.target.value);setMessage('');}}>{apps.map(app=><option value={app.id} key={app.id}>{app.name}</option>)}</select></label><label>Local app folder<select value={folder} onChange={event=>setFolder(event.target.value)}><option value="">Match by app name</option>{folders.map(name=><option key={name} value={name}>{name.trim()}</option>)}</select></label><button className="button" disabled={!appId||busy} onClick={async()=>{setBusy(true);setMessage('');try{const response=await fetch('/api/assets/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appId,...(folder?{folder}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error);setAssets(data.assets);setFolder(data.folder||'');setMessage([`${data.assets.length} assets available. ${data.imported} local files checked.`,...data.warnings].join(' '));}catch(error){setMessage(error instanceof Error?error.message:'Sync failed.');}finally{setBusy(false);}}}>{busy?'Syncing…':'Sync local folder'}</button></div><p className="muted">Add files to Apps/{folder||'your app folder'}, then sync. Forge also syncs before generating concepts. Originals stay untouched. Template dumps are grouped separately in Template Swipes.</p>
 <div className="upload-bar"><label>Upload category<select value={category} onChange={event=>setCategory(event.target.value)}>{['PRODUCT','TEMPLATE','VIDEO','DEMO','OUTPUT','MARKETING','BRAND','OTHER'].map(value=><option key={value}>{value}</option>)}</select></label><label className="button secondary">Add images or videos<input type="file" multiple accept="image/*,video/mp4,video/quicktime,video/webm" disabled={!appId||busy} className="file-input" onChange={async event=>{const files=Array.from(event.target.files||[]);if(!files.length)return;setBusy(true);const form=new FormData();form.set('appId',appId);form.set('category',category);files.forEach(file=>form.append('files',file));try{const response=await fetch('/api/assets/upload',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage(`${data.assets.length} files added. ${data.warnings.join(' ')}`);await load(appId);}catch(error){setMessage(error instanceof Error?error.message:'Upload failed.');}finally{setBusy(false);event.target.value='';}}}/></label><input aria-label="Search assets" placeholder="Search your assets…" value={query} onChange={event=>setQuery(event.target.value)}/></div>
 {message&&<p role="status" className="info-strip">{message}</p>}<div className="asset-grid">{filtered.map(asset=><button className="library-asset" key={asset.id} onClick={()=>setViewer(asset)}>{asset.type==='image'?<img src={assetUrl(asset.id,true)} alt={asset.filename} loading="lazy"/>:<div className="video-placeholder">▶<span>Video</span></div>}<strong>{asset.filename}</strong><small>{asset.category} · {asset.sourceKind==='app-store'?'App Store':'Local asset'}</small></button>)}</div>{!assets.length&&<p className="info-strip">Sync your app folder or add files to start building your creative library.</p>}
 {viewer&&<div className="asset-overlay" role="dialog" aria-modal="true" aria-label={viewer.filename}><button className="button" autoFocus onClick={()=>setViewer(null)}>Close preview</button>{viewer.type==='image'?<img src={assetUrl(viewer.id,true)} alt={viewer.filename}/>:<video src={assetUrl(viewer.id)} controls/>}<p>{viewer.filename} · {viewer.width} × {viewer.height}</p></div>}</>;
}
