'use client';
import styles from './video-workspace.module.css';
import {VideoEditor} from './video-editor';
import {VideoResults,useLatestVideoBatch} from './video-results';
import {useEffect,useState} from 'react';
import type {Asset} from '@/lib/models';
import type {HookVideo} from '@/lib/hook-video';
import {footageRole} from '@/lib/asset-policy';
import {assetUrl} from './asset-library';
import {TextBankEditor,type SavedTexts} from './text-bank-editor';
export function HookWorkspace({appId,assets}:{appId:string;assets:Asset[]}){
 const [count,setCount]=useState(6),[bank,setBank]=useState<SavedTexts>({hooks:[],ctas:[]}),[audio,setAudio]=useState<'muted'|'original'>('original'),[videos,setVideos]=useState<HookVideo[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState<HookVideo|null>(null),[excluded,setExcluded]=useState<string[]>([]);
 const latest=useLatestVideoBatch(appId,'hook');
 const hooks=assets.filter(a=>a.type==='video'&&footageRole(a)==='hook'),demos=assets.filter(a=>a.type==='video'&&footageRole(a)==='demo');
 useEffect(()=>{let active=true;setVideos([]);setExcluded([]);setPreview(null);if(appId)void Promise.all([fetch(`/api/text-bank?appId=${appId}`).then(r=>r.json()),fetch(`/api/hook-videos?appId=${appId}`).then(r=>r.json())]).then(([b,v])=>{if(active){if(b.error)throw new Error(b.error);setBank(b);setVideos(Array.isArray(v)?v:[]);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[appId]);
 async function post(url:string,body:unknown){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
 async function render(items:HookVideo[]){for(const [i,v]of items.entries()){setBusy(`Rendering ${i+1}/${items.length}…`);setVideos(values=>values.map(item=>item.id===v.id?{...item,status:'rendering'}:item));try{const done=await post(`/api/hook-videos/${v.id}/render`,{});setVideos(values=>values.map(item=>item.id===done.id?done:item));}catch(e){setVideos(values=>values.map(item=>item.id===v.id?{...item,status:'failed'}:item));throw e;}}}
 async function act(fn:()=>Promise<void>){setError('');setBusy('Preparing random pairs…');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Could not finish.');}finally{setBusy('');}}
 return <section className={styles.workspace}><section className={styles.options}><div className={styles.bar}><div><h2>Hook + Demo</h2><p className="muted">{hooks.length} hooks · {demos.length} demos · no trimming</p></div><div className="library-controls"><label>Videos<input type="number" min={1} max={50} value={count} disabled={!!busy} onChange={e=>setCount(Number(e.target.value))}/></label><label>Audio<select value={audio} disabled={!!busy} onChange={e=>setAudio(e.target.value as typeof audio)}><option value="original">Keep original</option><option value="muted">Mute</option></select></label><button className="button" disabled={!!busy||!hooks.some(a=>!excluded.includes(a.id))||!demos.some(a=>!excluded.includes(a.id))||!bank.hooks.length} onClick={()=>void act(async()=>{const created:HookVideo[]=await post('/api/hook-videos',{appId,count,audio,texts:bank.hooks,hookAssetIds:hooks.filter(a=>!excluded.includes(a.id)).map(a=>a.id),demoAssetIds:demos.filter(a=>!excluded.includes(a.id)).map(a=>a.id)});setVideos(values=>[...created,...values]);latest.remember(created);await render(created);})}>Make {count} videos</button></div></div><TextBankEditor appId={appId} bank={bank} onChange={setBank} disabled={!!busy}/><details><summary>Footage · all clips included by default</summary><div className="compact-footage">{[...hooks,...demos].map(a=><label key={a.id} title={a.filename}><input type="checkbox" checked={!excluded.includes(a.id)} disabled={!!busy} onChange={()=>setExcluded(values=>values.includes(a.id)?values.filter(id=>id!==a.id):[...values,a.id])}/>{a.thumbnailPath&&<img src={assetUrl(a.id,true)} alt="" loading="lazy"/>}<span>{footageRole(a)} · {a.filename}</span></label>)}</div></details></section>{busy&&<p role="status" className="video-progress">{busy} Keep this page open.</p>}{error&&<p role="alert" className="error-message">{error}</p>}<VideoResults videos={videos} latestIds={latest.ids} busy={!!busy} endpoint="hook-videos" onEdit={setPreview} onRender={items=>void act(()=>render(items))}/>{preview&&<VideoEditor kind="hook" video={preview} assets={assets} bank={bank} onClose={()=>setPreview(null)} onSaved={saved=>{setVideos(values=>values.map(v=>v.id===saved.id?saved:v));setPreview(saved);}}/>}</section>;
}
