'use client';
import {useRef,useState} from 'react';
import type {ImageCrop} from '@/lib/crop';
import {fullCrop} from '@/lib/crop';
import {assetUrl} from './asset-library';
export function ImageCropDialog({assetId,initial,onApply,onClose}:{assetId:string;initial?:ImageCrop;onApply:(crop:ImageCrop)=>void;onClose:()=>void}){
 const [crop,setCrop]=useState(initial||fullCrop);const anchor=useRef<{x:number;y:number}|null>(null);
 function point(e:React.PointerEvent<HTMLDivElement>){const box=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(e.clientY-box.top)/box.height))};}
 return <div className="asset-overlay" role="dialog" aria-modal="true" aria-label="Crop image"><div className="crop-dialog"><div className="compact-heading"><h2>Crop image</h2><button className="text-button" onClick={onClose}>Cancel</button></div><p>Drag across the image to keep that area. The rest of the slide stays black.</p><div className="crop-stage" onPointerDown={e=>{anchor.current=point(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!anchor.current)return;const p=point(e),a=anchor.current,x=Math.min(0.99,a.x,p.x),y=Math.min(0.99,a.y,p.y);setCrop({x,y,width:Math.min(1-x,Math.max(0.01,Math.abs(p.x-a.x))),height:Math.min(1-y,Math.max(0.01,Math.abs(p.y-a.y)))});}} onPointerUp={()=>{anchor.current=null;}} onPointerCancel={()=>{anchor.current=null;}}><img draggable={false} src={assetUrl(assetId,true)} alt="Drag to select the image crop"/><div className="crop-selection" style={{left:crop.x*100+'%',top:crop.y*100+'%',width:crop.width*100+'%',height:crop.height*100+'%'}}/></div><div className="compact-two"><label>Crop width<input aria-label="Crop width" type="range" min={1} max={100-crop.x*100} value={crop.width*100} onChange={e=>setCrop({...crop,width:Number(e.target.value)/100})}/></label><label>Crop height<input aria-label="Crop height" type="range" min={1} max={100-crop.y*100} value={crop.height*100} onChange={e=>setCrop({...crop,height:Number(e.target.value)/100})}/></label></div><div className="form-actions"><button className="button secondary" onClick={()=>setCrop(fullCrop)}>Reset</button><button className="button" onClick={()=>onApply(crop)}>Apply crop</button></div></div></div>;
}
