'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { App } from '@/lib/models';
import type { LurkerItem } from '@/lib/lurker';
export function LurkerWorkspace({apps,initialItems}:{apps:App[];initialItems:LurkerItem[]}){
 const router=useRouter();const [items,setItems]=useState(initialItems);const [url,setUrl]=useState('');const [notes,setNotes]=useState('');const [title,setTitle]=useState('');const [image,setImage]=useState<File|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [appId,setAppId]=useState(apps[0]?.id||'');const [type,setType]=useState('slideshow');
 async function reload(){setItems(await fetch('/api/inspirations').then(response=>response.json()));}
 async function analyze(id:string){const response=await fetch(`/api/inspirations/${id}/analyze`,{method:'POST',headers:{'Content-Type':'application/json'}});const result=await response.json();if(!response.ok)throw new Error(result.error);}
 return <><form className="import-entry" onSubmit={async event=>{event.preventDefault();setBusy('Saving the post and checking public metadata…');setError('');const form=new FormData();form.set('url',url);form.set('notes',notes);form.set('title',title);if(image)form.set('image',image);try{const response=await fetch('/api/inspirations',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);await reload();setBusy('Codex is analyzing the creative format…');await analyze(result.id);setUrl('');setNotes('');setTitle('');setImage(null);}catch(error){setError(error instanceof Error?error.message:'Could not analyze this post.');}finally{try{await reload();}catch{setError('The reference may be saved, but the list could not refresh. Reload this page.');}setBusy('');}}}>
 <h2>Found something worth remixing?</h2><p className="muted">Paste a social post URL. Save the reference, understand its format, then adapt it for your app.</p><div className="import-url-row lurker-url"><input type="url" required aria-label="Social post URL" placeholder="Paste a TikTok, Instagram, Pinterest, YouTube, LinkedIn, or X post URL" value={url} disabled={Boolean(busy)} onChange={event=>setUrl(event.target.value)}/><button className="button" disabled={Boolean(busy)||!url}>Save & analyze</button></div><details className="lurker-context" open={Boolean(notes||title)}><summary>Add context or a screenshot</summary><label>Title (optional)<input value={title} maxLength={300} onChange={event=>setTitle(event.target.value)}/></label><label>Notes / caption / what happens in the post<textarea rows={4} value={notes} maxLength={8000} onChange={event=>setNotes(event.target.value)} placeholder="Describe the opening hook, sequence, visuals, and CTA. Useful when the platform blocks access."/></label><label>Reference screenshot<input type="file" accept="image/*" onChange={event=>setImage(event.target.files?.[0]||null)}/></label></details><p className="generation-disclosure">Codex uses accessible caption metadata, your notes, and your screenshot. It does not claim to watch blocked videos. Reference media is never added to your production asset library.</p></form>
 {busy&&<p role="status" className="info-strip">{busy}</p>}{error&&<p role="alert" className="error-message">{error}</p>}
 <div className="library-controls remix-controls"><label>Remix for<select value={appId} onChange={event=>setAppId(event.target.value)}>{apps.map(app=><option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Output workflow<select value={type} onChange={event=>setType(event.target.value)}><option value="slideshow">Slideshow</option><option value="carousel">Carousel</option><option value="hook-demo">Hook + Demo storyboard</option><option value="template-video">Template Videos (batch of 3)</option></select></label></div>
 <div className="lurker-grid">{items.map(item=><article className="lurker-card" key={item.id}><span className="eyebrow">{item.platform} · {item.analysisStatus}</span><h2>{item.analysisJson.name||item.title||'Saved inspiration'}</h2><a href={item.url} target="_blank" rel="noreferrer" className="inline-link">View original post ↗</a><p className="muted">{item.retrievalNote}</p>{item.analysisStatus==='complete'?<><p>{item.analysisJson.description}</p><dl><dt>Hook pattern</dt><dd>{item.analysisJson.hookPattern}</dd><dt>Structure</dt><dd>{item.analysisJson.structure?.join(' → ')}</dd><dt>Visual mechanic</dt><dd>{item.analysisJson.visualMechanic}</dd><dt>Remix direction</dt><dd>{item.analysisJson.remixAdvice}</dd></dl><p className="analysis-limit">Evidence limits: {item.analysisJson.limitations}</p><button className="button" disabled={!appId||Boolean(busy)} onClick={async()=>{setBusy('Codex is remixing this format for your app…');setError('');try{const response=await fetch(`/api/inspirations/${item.id}/remix`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appId,type})});const result=await response.json();if(!response.ok)throw new Error(result.error);router.push(result.url);}catch(error){setError(error instanceof Error?error.message:'Remix failed.');setBusy('');}}}>Remix for {apps.find(app=>app.id===appId)?.name||'an app'}</button></>:<p className="muted">Add notes or a screenshot to give Codex enough evidence to analyze this post.</p>}<button className="text-button context-button" disabled={Boolean(busy)} onClick={()=>{setUrl(item.url);setNotes(item.notes);setTitle(item.title);setError('');window.scrollTo({top:0,behavior:'smooth'});}}>Add context / edit saved reference</button></article>)}</div>{!items.length&&<p className="info-strip">Your creative memory starts with one interesting post.</p>}</>;
}
