'use client';
import styles from './video-workspace.module.css';
import {VideoEditor} from './video-editor';
import {VideoResults,useLatestVideoBatch} from './video-results';
import {useAppSelection} from './use-app-selection';
import {useEffect,useState} from 'react';
import type {App,Asset} from '@/lib/models';
import type {TemplateSet,TemplateVideo} from '@/lib/template-video';
import {assetUrl} from './asset-library';
import {TextBankEditor,type SavedTexts} from './text-bank-editor';
export function TemplateVideos({apps,initialAppId}:{apps:App[];initialAppId?:string}){
 const [appId,setAppId]=useAppSelection(apps,initialAppId),[sets,setSets]=useState<TemplateSet[]>([]),[selected,setSelected]=useState<string[]>([]),[videos,setVideos]=useState<TemplateVideo[]>([]),[hold,setHold]=useState(2),[caption,setCaption]=useState(''),[ctaText,setCtaText]=useState(''),[cta,setCta]=useState(true),[brandId,setBrandId]=useState(''),[brands,setBrands]=useState<Asset[]>([]),[bank,setBank]=useState<SavedTexts>({hooks:[],ctas:[]}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[randomCount,setRandomCount]=useState(3),[preview,setPreview]=useState<TemplateVideo|null>(null),[varyCta,setVaryCta]=useState(true),[vary,setVary]=useState(true),[variations,setVariations]=useState(1);
 const latest=useLatestVideoBatch(appId,'template');
 async function load(id:string,active=()=>true){const [response,media,texts]=await Promise.all([fetch(`/api/template-sets?appId=${id}`),fetch(`/api/assets?appId=${id}`),fetch(`/api/text-bank?appId=${id}`)]);const data=await response.json();if(!response.ok)throw new Error(data.error);const b=await texts.json(),a=await media.json();if(b.error)throw new Error(b.error);if(!active())return;setSets(data.sets);setVideos(data.videos);setBank(b);setCaption(b.hooks[0]||'');setCtaText(b.ctas[0]||'');setBrands((a.assets||[]).filter((asset:Asset)=>asset.category==='BRAND'||asset.sourceKind==='app-store'));}
 useEffect(()=>{let active=true;setSelected([]);setQuery('');setPreview(null);setVary(true);setSets([]);setVideos([]);setBrandId('');setError('');if(appId)void load(appId,()=>active).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[appId]);
 async function post(url:string,body:unknown){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
 async function act(fn:()=>Promise<void>){setBusy('Preparing…');setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Could not finish.');}finally{setBusy('');}}
 async function render(items:TemplateVideo[]){for(const [i,v]of items.entries()){setBusy(`Rendering ${i+1}/${items.length}…`);setVideos(values=>values.map(item=>item.id===v.id?{...item,status:'rendering'}:item));try{const done=await post(`/api/template-videos/${v.id}/render`,{});setVideos(values=>values.map(item=>item.id===done.id?done:item));}catch(e){setVideos(values=>values.map(item=>item.id===v.id?{...item,status:'failed'}:item));throw e;}}}
 const maxSelected=Math.floor(50/variations);
 function pickRandom(){const pool=[...filtered];for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}setSelected(pool.slice(0,Math.min(randomCount,maxSelected)).map(s=>s.key));}
 const filtered=sets.filter(s=>`${s.name} ${s.source}`.toLowerCase().includes(query.toLowerCase()));
 return <section className={styles.workspace}>
 <div className={styles.bar}><label>App<select disabled={!!busy} value={appId} onChange={e=>setAppId(e.target.value)}>{apps.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Variations / template<select value={variations} disabled={!!busy} onChange={e=>setVariations(Number(e.target.value))}>{[1,2,3,5,10].map(n=><option key={n}>{n}</option>)}</select></label><span className={styles.spacer}/><button className="button secondary" disabled={!!busy} onClick={()=>void act(async()=>{await post('/api/assets/sync',{appId});await load(appId);})}>Sync files</button><button className="button" disabled={!!busy||!bank.hooks.length||!selected.length||selected.length*variations>50} onClick={()=>void act(async()=>{const created=await post('/api/template-videos',{appId,templateKeys:selected,variations,hold,caption,ctaEnabled:cta,ctaText,ctaAssetId:brandId||undefined,randomizeText:vary,randomizeCta:varyCta});setVideos(values=>[...created,...values]);latest.remember(created);await render(created);})}>Make {selected.length*variations} videos</button></div>
 <details className={styles.options}><summary>Text & timing · {vary?'random hooks':'fixed hook'} · {cta?varyCta?'random CTAs':'fixed CTA':'no CTA'} · {hold}s / slide</summary><div className={styles.settings}><label>Hook<select value={vary?'__random':caption} disabled={!!busy} onChange={e=>{setVary(e.target.value==='__random');if(e.target.value!=='__random')setCaption(e.target.value);}}><option value="__random">Random from hook bank</option>{bank.hooks.map((t,i)=><option key={i}>{t}</option>)}</select></label><label>CTA<select value={varyCta?'__random':ctaText} disabled={!!busy||!cta} onChange={e=>{setVaryCta(e.target.value==='__random');if(e.target.value!=='__random')setCtaText(e.target.value);}}><option value="__random">Random from CTA bank</option>{bank.ctas.map((t,i)=><option key={i}>{t}</option>)}</select></label><label>Slide hold<select value={hold} disabled={!!busy} onChange={e=>setHold(Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}s</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={cta} disabled={!!busy} onChange={e=>setCta(e.target.checked)}/>Branded CTA end card</label><label>Brand image<select disabled={!!busy||!cta} value={brandId} onChange={e=>setBrandId(e.target.value)}><option value="">Auto: app logo</option>{brands.map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label><div><button className="text-button" disabled={!!busy||bank.hooks.length<2} onClick={()=>{const texts=bank.hooks.filter(t=>t!==caption);setCaption(texts[Math.floor(Math.random()*texts.length)]);setVary(false);}}>Randomize hook</button><button className="text-button" disabled={!!busy||!cta||bank.ctas.length<2} onClick={()=>{const texts=bank.ctas.filter(t=>t!==ctaText);setCtaText(texts[Math.floor(Math.random()*texts.length)]);setVaryCta(false);}}>Randomize CTA</button></div></div><TextBankEditor appId={appId} bank={bank} onChange={setBank} disabled={!!busy}/></details>
 {busy&&<p role="status" className={styles.notice}>{busy} Keep this page open.</p>}{error&&<p role="alert" className="error-message">{error}</p>}
 <div className={styles.columns}><section className={styles.templates}><div className={styles.picker}><input aria-label="Search templates" value={query} placeholder={`Search all ${sets.length}`} onChange={e=>setQuery(e.target.value)}/><select aria-label="Random template count" value={randomCount} disabled={!!busy} onChange={e=>setRandomCount(Number(e.target.value))}>{[1,3,5,10,15,25,50].map(n=><option key={n}>{n}</option>)}</select><button className="button secondary" disabled={!!busy||!filtered.length} onClick={pickRandom}>Random ↻</button></div><p className={styles.count}>{filtered.length} folders · {selected.length} selected <button className="text-button" disabled={!!busy} onClick={()=>setSelected(filtered.slice(0,maxSelected).map(s=>s.key))}>All</button><button className="text-button" disabled={!!busy} onClick={()=>setSelected([])}>Clear</button></p>{selected.length*variations>50&&<p role="alert" className={styles.notice}>Reduce to 50 videos per batch.</p>}<div className={styles.templateList}>{filtered.map(set=><button disabled={!!busy||(!selected.includes(set.key)&&selected.length>=maxSelected)} aria-pressed={selected.includes(set.key)} title={set.source} className={styles.templateRow} key={set.key} onClick={()=>setSelected(values=>values.includes(set.key)?values.filter(key=>key!==set.key):[...values,set.key])}><span className={styles.strip}>{set.slides.map((id,i)=><img key={i} width={12} height={18} src={assetUrl(id,true)} alt={`Slide ${i+1}`} loading="lazy"/>)}</span><strong>{set.name}</strong><small>{selected.includes(set.key)?'✓':set.slides.length}</small></button>)}</div>{!filtered.length&&<p className={styles.notice}>{sets.length?'No matching folders.':'Sync to load Display Image folders.'}</p>}</section>
 <VideoResults videos={videos} latestIds={latest.ids} busy={!!busy} endpoint="template-videos" onEdit={setPreview} onRender={items=>void act(()=>render(items))}/></div>
 {preview&&<VideoEditor kind="template" video={preview} assets={brands} bank={bank} onClose={()=>setPreview(null)} onSaved={saved=>{setVideos(values=>values.map(v=>v.id===saved.id?saved:v));setPreview(saved);}}/>}</section>;
}
