'use client';
import {useEffect,useRef,useState} from 'react';
export interface SavedTexts {hooks:string[];ctas:string[];}
const lines=(text:string)=>text.split('\n').map(s=>s.trim()).filter(Boolean);
export function TextBankEditor({appId,bank,onChange,disabled=false}:{appId:string;bank:SavedTexts;onChange:(bank:SavedTexts)=>void;disabled?:boolean}){
 const [hooks,setHooks]=useState(bank.hooks.join('\n')),[ctas,setCtas]=useState(bank.ctas.join('\n')),[busy,setBusy]=useState(false),[error,setError]=useState(''),[kind,setKind]=useState<'hooks'|'ctas'>('hooks'),[count,setCount]=useState(25),[progress,setProgress]=useState('');const stop=useRef(false);
 useEffect(()=>{setHooks(bank.hooks.join('\n'));setCtas(bank.ctas.join('\n'));},[bank]);
 async function send(method:string,body:unknown){const r=await fetch('/api/text-bank',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({appId,...body as object})});const data=await r.json();if(!r.ok)throw new Error(data.error);return data as SavedTexts;}
 async function save(){setBusy(true);setError('');try{onChange(await send('PUT',{hooks:lines(hooks),ctas:lines(ctas)}));}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function add(){setBusy(true);setError('');stop.current=false;try{let current=await send('PUT',{hooks:lines(hooks),ctas:lines(ctas)});onChange(current);const target=Math.min(500,current[kind].length+count);while(current[kind].length<target&&!stop.current){setProgress(`Adding ${kind} · ${current[kind].length}/${target} saved`);const before=current[kind].length;current=await send('POST',{kind,count:Math.min(25,target-before)});onChange(current);if(current[kind].length===before)throw new Error('No new unique lines were returned. Your bank is saved; try again.');}setProgress(`${current[kind].length} ${kind} saved`);}catch(e){setError(e instanceof Error?e.message:'Could not add text.');}finally{setBusy(false);}}
 const invalid=lines(hooks).length>500||lines(ctas).length>500;
 return <details className="text-bank-editor"><summary>Text banks · {bank.hooks.length}/500 hooks · {bank.ctas.length}/500 CTAs</summary><p className="muted">Paste one line per option. Add with Codex keeps existing text and saves each batch of 25.</p><div className="compact-two"><label>Hooks · {lines(hooks).length}/500<textarea rows={5} value={hooks} disabled={busy||disabled} onChange={e=>setHooks(e.target.value)}/></label><label>CTAs · {lines(ctas).length}/500<textarea rows={5} value={ctas} disabled={busy||disabled} onChange={e=>setCtas(e.target.value)}/></label></div><div className="bank-actions"><button className="button secondary" disabled={busy||disabled||invalid} onClick={()=>void save()}>Save bank</button><select aria-label="Bank to expand" disabled={busy||disabled} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="hooks">Hooks</option><option value="ctas">CTAs</option></select><select aria-label="Number of new lines" disabled={busy||disabled} value={count} onChange={e=>setCount(Number(e.target.value))}>{[25,50,100,250,500].map(n=><option key={n} value={n}>Add {n}</option>)}</select><button className="button secondary" disabled={busy||disabled||invalid||lines(kind==='hooks'?hooks:ctas).length>=500} onClick={()=>void add()}>Add with Codex</button>{busy&&<button className="text-button" onClick={()=>{stop.current=true;}}>Stop after this batch</button>}</div>{progress&&<p role="status">{progress}</p>}{(error||invalid)&&<p role="alert" className="error-message">{error||'Keep each bank within 500 lines.'}</p>}</details>;
}
